### ISSUE TITLE
與open web ui 合作的可能

### ISSUE THREAD

**Issue by 123hi123** [donzell888/fast-tts#3]
我希望可以把作者的這個東西替換掉web ui的語音輸出功能
但我很菜
如果可以希望作者可以給我一些方向 或想法 讓我研究
open web ui :https://github.com/open-webui/open-webui

**Comment by donzell888** [comment]
理论上是可以的。可以在open-webui项目中调用fast-tts中的“/generate”接口来获取音频播放url。在网页中使用“audio”标签加载播放。不过不好意思我不了解open web ui这个项目，你应该先阅读和调试它的代码来确定。

**Comment by 123hi123** [comment]
多謝 我再來去試試看怎麼搞

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/b054fcb0-52f2-4e50-a723-960c2b3c0e31)
目前的嘗試是這個樣子但不知道為甚麼沒有聲音 左邊是修改後代碼 右邊是修改前
https://www.bilibili.com/video/BV1C4YGeUE1S/?spm_id_from=333.880.my_history.page.click&vd_source=6dd8661256b580405b1a8d88d4763d8c
根據這個影片中的20:14後面改的

**Comment by donzell888** [comment]
可能是数据类型不对导致的，generate API中返回的不是音频流数据而是音频Url。拿到音频Url需要再发起一次网络请求获取音频流数据。

**Comment by 123hi123** [comment]
所以作者你的代碼是接受文字輸入然後使用url回覆這樣
那我好奇那個音頻文件都存在哪裡啊，是不是會越轉換檔案越多

**Comment by donzell888** [comment]
音频不会越转越多的，媒体内容不会写盘，都是在内存上进行的。浏览器关闭后就会自动清理了，不会占用资源的。

**Comment by 123hi123** [comment]
多謝告知 之後再來去修改看看 然後我最近發現 lobechat 裡面自帶的語音都和作者你的好像
