### ISSUE TITLE
轉錄的時候卡住

### ISSUE THREAD

**Issue by 123hi123** [donzell888/fast-tts#6]
![image](https://github.com/user-attachments/assets/1fa32e28-20b8-48e8-a5fc-a7ce8a01089a)
使用文本如下
`Here's an analysis of the key words and phrases you requested:

1. eligible (符合條件的)
  字源：來自古法語 "eligible"，源自拉丁語 "eligere"，意為 "選擇"。"e-" 意為 "出"，"legere" 意為 "選擇"。
  例句：Only eligible voters can participate in the election.
  中文：只有符合條件的選民才能參與選舉。
  原文用例："The CDC stated that adults who completed their primary vaccine series are eligible for the updated booster if it has been at least two months since their previous vaccine."
  中文：疾控中心聲明，完成初始疫苗系列接種的成年人如果距離上次接種至少兩個月，就有資格接種更新後的加強針。
  
2. boosted (加強的)
  字源：來自古英語 "bōt"，意為 "幫助，好處"。
  例句：The economy was boosted by new government policies.
  中文：經濟因新的政府政策而得到提振。
  原文用例："...three months before getting boosted."
  中文：...在接種加強針之前的三個月。
  
3. counterproductive (適得其反的)
  字源：由 "counter-"（反） 和 "productive"（有成效的）組成。"productive" 源自拉丁語 "producere"，意為 "產生"。
  例句：The new policy proved to be counterproductive and actually increased crime rates.
  中文：新政策被證明是適得其反的，實際上增加了犯罪率。
  原文用例："Such a short interval is not optimal if we are aiming for robust fall- and winter-long protection, and could even be counterproductive."
  中文：如果我們的目標是獲得強大的秋冬季長期保護，這樣短的間隔並不理想，甚至可能適得其反。
  
4. immunologic (免疫學的)
  字源：由 "immuno-"（免疫）和 "-logic"（學問）組成。"immuno-" 源自拉丁語 "immunis"，意為 "免除"。
  例句：The immunologic response to the vaccine was stronger than expected.
  中文：對疫苗的免疫學反應比預期的更強。
  原文用例："...updated immunologic studies, and recognition that millions of Americans had postvaccination infections..."
  中文：...更新的免疫學研究，以及認識到數百萬美國人在接種疫苗後仍然感染...
  
5. postvaccination (接種疫苗後的)
  字源：由 "post-"（後）和 "vaccination"（疫苗接種）組成。"vaccination" 源自拉丁語 "vacca"，意為 "牛"，因早期疫苗是用牛痘製作的。
  例句：Postvaccination symptoms are usually mild and short-lived.
  中文：接種疫苗後的症狀通常輕微且短暫。
  原文用例："...millions of Americans had postvaccination infections with Omicron variants this year..."
  中文：...數百萬美國人今年在接種疫苗後仍感染了奧密克戎變種...
  
6. reinfection (再感染)
  字源：由 "re-"（再次）和 "infection"（感染）組成。"infection" 源自拉丁語 "inficere"，意為 "浸染"。
  例句：The risk of reinfection is lower for those who have been vaccinated.
  中文：對於已接種疫苗的人來說，再感染的風險較低。
  原文用例："...strong current protection against reinfection with BA.5."
  中文：...對 BA.5 再感染的強大當前保護。
  
7. amplified (放大的)
  字源：源自拉丁語 "ampliare"，意為 "擴大"。
  例句：The sound was amplified by the acoustics of the room.
  中文：聲音被房間的音響效果放大了。
  原文用例："...demonstrating a higher antibody response, amplified T cells, and enriched memory B cells with a longer time between doses."
  中文：...證明了在劑量之間間隔時間較長時，會產生更高的抗體反應，增強的 T 細胞，以及豐富的記憶 B 細胞。
  
8. enriched (豐富的)
  字源：源自古法語 "enrichir"，由 "en-"（使...） 和 "riche"（富有的）組成。
  例句：The soil was enriched with organic fertilizers.
  中文：土壤被有機肥料滋養得更加肥沃。
  原文用例：同上
  
9. neutralizing (中和的)
  字源：源自拉丁語 "neutralis"，意為 "中性的"。
  例句：The neutralizing antibodies help protect against virus infection.
  中文：中和抗體有助於抵禦病毒感染。
  原文用例："A booster provides antibody protection for at least six months, according to a recent study, increasing both neutralizing antibodies and memory B cells."
  中文：根據最近的一項研究，加強針可提供至少六個月的抗體保護，同時增加中和抗體和記憶 B 細胞。
  
10. robust (強健的)
  字源：源自拉丁語 "robustus"，意為 "橡木製的，堅固的"。
  例句：The company has a robust financial strategy.
  中文：該公司有一個強健的財務策略。
  原文用例："Such a short interval is not optimal if we are aiming for robust fall- and winter-long protection..."
  中文：如果我們的目標是獲得強大的秋冬季長期保護，這樣短的間隔並不理想...
  
11. third-dose (第三劑)
  字源：由 "third"（第三）和 "dose"（劑量）組成。"dose" 源自希臘語 "dosis"，意為 "給予"。
  例句：The third-dose booster is recommended for certain high-risk groups.
  中文：建議某些高風險群體接種第三劑加強針。
  原文用例："Another study showed that memory B cells continue to mature for approximately six months after vaccination or infection. B cell immunity—as well as T cell immunity to COVID vaccines—provided protection against severe illness and did not lead to high levels of hospitalization as BA.5 became dominant this summer."
  中文：另一項研究表明，記憶 B 細胞在接種疫苗或感染後約六個月內持續成熟。B 細胞免疫力——以及對 COVID 疫苗的 T 細胞免疫力——提供了對重症的保護，並且在 BA.5 今年夏天成為主導株時並未導致高住院率。
  
12. immunity (免疫力)
  字源：源自拉丁語 "immunitas"，意為 "豁免"。
  例句：Regular exercise can boost your immunity.
  中文：規律運動可以增強你的免疫力。
  原文用例：同上
  
13. hospitalization (住院)
  字源：源自拉丁語 "hospitalis"，意為 "友好的，好客的"。
  例句：The new treatment reduced the rate of hospitalization.
  中文：新的治療方法降低了住院率。
  原文用例：同上
  
14. plateau (平台期)
  字源：源自法語，意為 "平坦的土地"。
  例句：The company's growth has reached a plateau.
  中文：公司的增長已達到平台期。
  原文用例："The antibody-level plateau at the six-month mark would thus signal an ideal time to boost with a BA.4/5-focused vaccine..."
  中文：六個月時的抗體水平平台期因此可能標誌著接種針對 BA.4/5 的疫苗加強針的理想時機...
  
15. postboosting (加強接種後)
  字源：由 "post-"（後）和 "boosting"（加強）組成。
  例句：Postboosting antibody levels were significantly higher.
  中文：加強接種後的抗體水平顯著提高。
  原文用例："...increase postboosting. To put it another way, high levels of circulating antibodies from short-interval boosting may limit the added protection of another booster."
  中文：...增加接種後的效果。換句話說，短間隔加強接種產生的高水平循環抗體可能會限制另一次加強針的額外保護作用。
  
16. abrogates (廢除)
  字源：源自拉丁語 "abrogare"，意為 "廢除，取消"。
  例句：The new law abrogates the previous regulations.
  中文：新法律廢除了先前的規定。
  原文用例："Another recent study, by the NIH, showed that giving a booster two months after a recent infection actually abrogates effective B cell responses."
  中文：國立衛生研究院的另一項最新研究表明，在最近感染後兩個月內接種加強針實際上會抑制有效的 B 細胞反應。
  
17. tabulation (表格化)
  字源：源自拉丁語 "tabula"，意為 "板，表格"。
  例句：The data tabulation process took several hours.
  中文：數據表格化的過程花了幾個小時。
  原文用例："...vastly exceeded the official tabulation."
  中文：...遠遠超過了官方統計。
  
18. extrapolated (推斷的)
  字源：源自拉丁語 "extra"（超出）和 "polare"（磨光，修飾）。
  例句：The future trends were extrapolated from current data.
  中文：未來趨勢是從當前數據推斷出來的。
  原文用例："The benefit of this degree of population immunity can be extrapolated from a recent study out of Portugal that shows..."
  中文：這種程度的人群免疫力的好處可以從葡萄牙最近的一項研究中推斷出來，該研究表明...
  
19. contrary (相反的)
  字源：源自拉丁語 "contrarius"，意為 "對立的"。
  例句：Contrary to popular belief, the Earth is not perfectly round.
  中文：與普遍看法相反，地球並不是完全圓的。
  原文用例："...contrary to previous concerns about waning immunity..."
  中文：...與先前關於免疫力減弱的擔憂相反...
  
20. strains (毒株)
  字源：源自古法語 "estreindre"，意為 "拉緊"。在生物學中，指生物的特定品系或變種。
  例句：The new vaccine is effective against multiple strains of the virus.
  中文：新疫苗對病毒的多種毒株都有效。
  原文用例："...for BA.5 reinfection, that infection from earlier Omicron strains BA.1/2 provides upwards of 75.3% protection against reinfection with BA.5."
  中文：...對於 BA.5 再感染，早期奧密克戎毒株 BA.1/2 的感染提供了高達 75.3% 的對 BA.5 再感染的保護。
  
21. prolongs (延長)
  字源：源自拉丁語 "prolongare"，由 "pro-"（向前）和 "longus"（長的）組成。
  例句：Regular exercise prolongs life expectancy.
  中文：規律運動延長了預期壽命。
  原文用例："All this data means there is a high amount of active population-level immunity to COVID-19 in the U.S. that is protective against severe disease. Our booster strategy should recognize this existing immunity and seek to build upon it in a manner that prolongs the protection of the new shot through the winter."
  中文：所有這些數據意味著美國存在高水平的針對 COVID-19 的活躍人群免疫力，可以預防重症。我們的加強針策略應該認識到這種既有免疫力，並尋求在此基礎上進行構建，以延長新疫苗在整個冬季的保護作用。
  
22. stunt (阻礙)
  字源：源自古英語 "stunt"，意為 "切短，阻止生長"。
  例句：Lack of nutrients can stunt a child's growth.
  中文：營養不足可能會阻礙兒童的生長。
  原文用例："Short-interval repeat boosting or boosting too soon after a postvaccination infection will limit the neutralizing antibody response and could stunt the expansion of memory B cells."
  中文：短間隔重複加強或在接種疫苗後感染後過快加強將限制中和抗體反應，並可能阻礙記憶 B 細胞的擴展。
  
23. imperative (至關重要的)
  字源：源自拉丁語 "imperare"，意為 "命令"。
  例句：It is imperative that we act quickly to address climate change.
  中文：我們必須迅速採取行動應對氣候變化，這是至關重要的。
  原文用例："It is imperative to increase trust in public health by emphasizing protecting those most at risk of severe breakthroughs (e.g., older people and those who are immunocompromised)."
  中文：通過強調保護那些最容易出現嚴重突破性感染的人（例如老年人和免疫功能低下的人），來增加公眾對公共衛生的信任，這一點至關重要。`
本地運行 卡在圖片中的秒數
過了大概五分鐘後才回來

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/31bd11dc-122b-4366-baa9-4ee368b7380c)
又卡了
但之前也有轉錄過更長的
不確定是怎麼回事

**Comment by donzell888** [comment]
我刚试了下你上面的文本，发现是可以转换成功的。可能是其它问题导致的，可以用浏览器调试看看有没有输出错误信息。

**Comment by donzell888** [comment]
参数是用url GET方式来传递的。所以文本过长会有影响。可以分段转换试试？或者换个浏览器试试(有些浏览器会限制url的长度)？

**Comment by 123hi123** [comment]
多謝測試
也有可能是我內存爆了 當初16g的內存現在捨不得拆了
