### ISSUE TITLE
Fast-tts不能在本地或者docker里运行

### ISSUE THREAD

**Issue by wangqiang-kubota** [donzell888/fast-tts#8]
我成功的搭建了环境，但是运行的时候，提示
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url='wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=6A5AA1D4EAFF4E9FB37E23D68491D6F4&ConnectionId=511a1188b66f46af8d9ff55643793491'
，请问这个是缺少配置或者如何解决这个问题？

下面是我的Dockerfile：
`
ARG PYTHON_VERSION=3.11.9
FROM docker.io/library/python:${PYTHON_VERSION}-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y gcc build-essential python3-dev libsox-dev gunicorn && \
    apt-get install -y ffmpeg libsm6 libxext6 libavutil-dev libsox-fmt-all git && \
    apt-get install -y --no-install-recommends g++ make python3-wheel espeak-ng libsndfile1-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
 
WORKDIR /app

USER root

COPY . .

CMD ["python", "server.py"] `

**Comment by donzell888** [comment]
可能是TTS依赖的问题，已经更新了。你重新检下来试试

**Comment by wangqiang-kubota** [comment]
我试了，确实可以了，非常感谢！
